### ISSUE TITLE
Arp lookup code

### ISSUE THREAD

**Issue by sandles** [justintaddei/arp-lookup#228]
I found that using the command 'arp -a' is a little slow and sometimes really slow. This is something to do with arp doing dns lookups. Have you considered using 'arp -an' instead to disable dns. It solved a few problems for me with timeouts.

Not sure if there is any other implications of this change, just thought I would mention it.

Cheers

**Comment by justintaddei** [comment]
I can't believe I'm only seeing this nearly a year later! Somehow it slipped under my radar :)

This doesn't appear to have an equivalent on Windows but may be worth providing as an option for those darwin machines. Thank you for bringing this up!

**Comment by justintaddei** [comment]
Resolved by #363
